// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client-comm.proto

package org.client.protos;

public final class ClientComm {
  private ClientComm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stream_UploadFileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stream_UploadFileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stream_UploadFileReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stream_UploadFileReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stream_DownloadFileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stream_DownloadFileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stream_DownloadFileReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stream_DownloadFileReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021client-comm.proto\022\006stream\"E\n\021UploadFil" +
      "eRequest\022\020\n\010filename\030\001 \001(\t\022\017\n\007payload\030\002 " +
      "\001(\014\022\r\n\005token\030\003 \001(\t\"!\n\017UploadFileReply\022\016\n" +
      "\006status\030\001 \001(\t\"6\n\023DownloadFileRequest\022\020\n\010" +
      "filename\030\001 \001(\t\022\r\n\005token\030\002 \001(\t\"$\n\021Downloa" +
      "dFileReply\022\017\n\007payload\030\002 \001(\0142\235\001\n\tStreamin" +
      "g\022D\n\nUploadFile\022\031.stream.UploadFileReque" +
      "st\032\027.stream.UploadFileReply\"\000(\001\022J\n\014Downl" +
      "oadFile\022\033.stream.DownloadFileRequest\032\031.s" +
      "tream.DownloadFileReply\"\0000\001B\025\n\021org.clien" +
      "t.protosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_stream_UploadFileRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_stream_UploadFileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stream_UploadFileRequest_descriptor,
        new java.lang.String[] { "Filename", "Payload", "Token", });
    internal_static_stream_UploadFileReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_stream_UploadFileReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stream_UploadFileReply_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_stream_DownloadFileRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_stream_DownloadFileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stream_DownloadFileRequest_descriptor,
        new java.lang.String[] { "Filename", "Token", });
    internal_static_stream_DownloadFileReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_stream_DownloadFileReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stream_DownloadFileReply_descriptor,
        new java.lang.String[] { "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
