// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client-comm.proto

package org.client.protos;

public interface DownloadFileReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.DownloadFileReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes payload = 2;</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();
}
