// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client-comm.proto

package org.client.protos;

public interface UploadFileReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.UploadFileReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
