// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: master-comm.proto

package org.master.protos;

public final class MasterComm {
  private MasterComm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stream_GetListOfFilesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stream_GetListOfFilesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stream_GetListOfFilesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stream_GetListOfFilesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021master-comm.proto\022\006stream\"(\n\025GetListOf" +
      "FilesRequest\022\017\n\007nodeips\030\001 \003(\t\"+\n\026GetList" +
      "OfFilesResponse\022\021\n\tfilenames\030\001 \003(\t2`\n\013Re" +
      "plication\022Q\n\016GetListOfFiles\022\035.stream.Get" +
      "ListOfFilesRequest\032\036.stream.GetListOfFil" +
      "esResponse\"\000B\025\n\021org.master.protosP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_stream_GetListOfFilesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_stream_GetListOfFilesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stream_GetListOfFilesRequest_descriptor,
        new java.lang.String[] { "Nodeips", });
    internal_static_stream_GetListOfFilesResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_stream_GetListOfFilesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stream_GetListOfFilesResponse_descriptor,
        new java.lang.String[] { "Filenames", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
